server:
  servlet:
    context-path: /api/v1
  port: 9020

spring:
  application:
    name: order_service

  datasource:
    url: jdbc:postgresql://localhost:5432/order_DB
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
