spring:
  application:
    name: inventory_service

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_DB
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  servlet:
    context-path: /api/v1

  port: 9010