spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
            - name: LoggingOrdersFilter
            - name: Authentication
              args:
                isEnabled: false
            - name: Authorization
              args:
                allowedRoles: ADMIN, SUPER_ADMIN

        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=x-Custom-Header, Sush
            - name: Authentication
              args:
                isEnabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secretKey: ${JWT_SECRET_KEY}

